name: Legg alle nye saker i repository til 'Team Kunde' prosjekt
on:
  issues:
    types:
      - opened

jobs:
  add-to-project-team-kunde:
    name: Add issue to 'Team Kunde' project 121
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Altinn/projects/121
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ env.repository_owner }}
          project_id: ${{ env.project_id_team_kunde }}
